name: Create-EC2

on: push

jobs:
  prepare:
    name : Run ec2 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Setup Repo
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy Instance
      id: deploy
      run: |
        aws cloudformation create-stack --stack-name TestStack --template-body file://Template.yaml
      continue-on-error: true
    - name: Update Instance
      if: steps.deploy.outcome != 'success'
      run: |
        aws cloudformation update-stack --stack-name TestStack --template-body file://Template.yaml
